on:
  pull_request:
  push:
    branches:
      - main

name: continuous-integration

env:
  CLIPPY_OPTIONS: "-D warnings"
  NU_VERSION: "0.84.0"

jobs:
  fmt-clippy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ""

      - name: Format
        run: cargo fmt --all -- --check

      - name: Setup dependencies
        run: |
          cargo add "nu-plugin@$NU_VERSION"
          cargo add "nu-protocol@$NU_VERSION" --features plugin
        shell: bash

      - name: Clippy
        run: cargo clippy --workspace -- $CLIPPY_OPTIONS

  tests:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-20.04]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ""

      - name: Setup dependencies
        run: |
          cargo add "nu-plugin@$NU_VERSION"
          cargo add "nu-protocol@$NU_VERSION" --features plugin
        shell: bash

      - name: Tests
        run: cargo test --workspace

  default-config:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          rustflags: ""

      - name: Install Nushell
        uses: hustcer/setup-nu@main
        with:
          version: '*'

      - name: Setup dependencies
        run: |
          cargo add "nu-plugin@$NU_VERSION"
          cargo add "nu-protocol@$NU_VERSION" --features plugin
        shell: bash

      - name: Install nu_plugin_explore
        run: |
          cargo install --path . --root /tmp/cargo-install/
          nu --commands $register /tmp/cargo-install/bin/nu_plugin_explore"
        shell: nu

      - name: Test the default config
        run: |
          $nu | explore (
              open examples/configuration/config.nuon
                  | insert colors (open examples/configuration/themes/dark.nuon)
                  | insert keybindings (open examples/configuration/keybindings.nuon)
          )
        shell: nu
